### PR TITLE
German translation for powered, support, proton-c and the categories directory

### PR DESCRIPTION
**Pull request by kuchosauronad0**
Sup,
I translated a couple more pages for the german translation. It would be nice to know which pages don't need translations due to being auto-generated, I know this is the case for keyboards.md at least; 

As always feedback concerning my use of commas and spellings etc is greatly appreciated.

Cheers

### CODE REVIEW

**Comment by noroadsleft** [comment]
To my knowledge, `_i18n/en/keyboards.md` is the only page that's auto-updated and should be ignored for translation purposes.

**Comment by noroadsleft** [comment]
Actually, can you revert that last commit? `_i18n/de/categories/keyboards.md` is a different file from the auto-generated `_i18n/en/keyboards.md` and serves a different purpose. `_i18n/de/categories/keyboards.md` is still purposeful when translating.

**Comment by kuchosauronad0** [comment]
Oops, yes I added it back. Since this PR and #85 translated some of the same files I'd suggest we go with #85 since I already reviewed it and it has the proper pronouns. And then just add the still missing files from #82 .

Should I delete:
* _i18n/de/powered.md
*  _i18n/de/support.md
* _i18n/de/sidebar.md (covered by #86 )

from this PR or can you cherry pick it?

@john2ksonn can you have a review proton-c.md and the others please? thanks

**Comment by noroadsleft** [comment]
> Oops, yes I added it back. Since this PR and `#85` translated some of the same files I'd suggest we go with `#85` since I already reviewed it and it has the proper pronouns. And then just add the still missing files from `#82`.

I like this idea; let's do that.

> Should I delete:
> 
>     * _i18n/de/powered.md
>     * _i18n/de/support.md
>     * _i18n/de/sidebar.md (covered by #86 )
> 
> 
> from this PR or can you cherry pick it?

It's actually easier on our end if you just delete those files from this branch. I could cherry-pick it but then I'd have to submit those changes in a new PR, which means you wouldn't get credit for those changes, and that doesn't sit right with me.

**Comment by noroadsleft** [comment]
@kuchosauronad0 Looks like I merged the German PRs in the wrong order. Could you rebase this branch, please?

**Comment by kuchosauronad0** [comment]
I hope I fixed it this time

**Review by noroadsleft — APPROVED** [review]
Looks good to me.

**Comment by noroadsleft** [comment]
Hmmm, interesting that https://github.com/qmk/qmk.fm/pull/82/commits/6fbc129c19b0c14bd2022b986129dd6676eb9362 seems to have been made in the future. GitHub weirdness, I'm sure.

**Pull request merged**
