### PR TITLE
Update Keyboard page generation script

### LINKED ISSUE #34: generate_keyboard_page.sh needs to be updated to use hex or bin files
Specifically: 
https://github.com/qmk/qmk.fm/blob/e613bbf5f54c5ad24f8a4e54ac24bea313ee9f40/_util/generate_keyboard_page.sh#L11-L14
This needs to be updated to look for hex ***or*** bin files. 

Unfortunately, I'm not quite sure how to do that, as bash/shell scripts are not something that I'm familiar enough with.

### PR DESCRIPTION
**Pull request by drashna**
Thanks @noroadsleft

This should link to the bin files when they're present, so that you can download the correct firmware image based on the board. 

This is .... untested, though. 
Also, this should be merged/rebased, and not squashed.  That way, we can revert the script change, and still have the ARM "hex" files removed.  If needed. 

Closes #34

### CODE REVIEW

**Review by skullydazed — APPROVED** [review]

**Comment by noroadsleft** [comment]
Looks like it's working as intended.

Still need to purge the bad files.

**Comment by drashna** [comment]
well, some of them were purged manually. but yeah....


Also, it looks like it is only producing the qmk toolbox link for bin files now.

**Comment by noroadsleft** [comment]
> Also, it looks like it is only producing the qmk toolbox link for bin files now.

Yeah, I just noticed that myself.

**Comment by drashna** [comment]
Fixed it.  It was a missing a bit on that line.  Next push should generate the links properly.

**Comment by noroadsleft** [comment]
Yeah I spotted the bug last night. I had a branch ready to go and then spotted that you'd used Collaborator Hax to commit directly to the repo to fix it when I went to open a PR. :rofl:

**Pull request merged**
