### PR TITLE
Fix typos on 'proton c' page

### PR DESCRIPTION
**Pull request by kuchosauronad0**
'soldermask' is spelled as two words and 'chose' can use another 'o' in this case.

### CODE REVIEW

**Review by noroadsleft — APPROVED** [review]
> 'soldermask' is spelled as two words

`Soldermask` in this context isn't actually wrong, but neither is spelling it as two words. It's like the difference between writing `ketchup` and `catsup`.

I'm fine with all of these changes.

**Comment by kuchosauronad0** [comment]
Sorry the catsup stuff goes over my head, I suppose it is a british vs american english thing?. My spellcheck picked up on the soldermask so I checked a dictionary and then google which has 193.000 ("soldermask") vs. 938.000 ("solder mask"). The missing o in choose would be actual typo on the page that needs fixing.
Cheers

**Review by fauxpark — APPROVED** [review]

**Comment by noroadsleft** [comment]
@kuchosauronad0 Yes, `ketchup` and `catsup` are two spellings in English for [the same thing](https://en.wikipedia.org/wiki/Ketchup). `Catsup` was the more common spelling in the U.S. for a while but now you mostly see `ketchup` here.

**Comment by noroadsleft** [comment]
Thanks!

**Pull request merged**
