### PR TITLE
[Vitamins Included] Make case work with 10mm bolts

### PR DESCRIPTION
**Pull request by Duckle29**
I made the nut wells deeper so that the case can be used with 10mm bolts, instead of the harder to find 12mm (here at least)

### CODE REVIEW

**Comment by mongrelion** [comment]
Is this backwards compatible with the 12mm bolts, though? or is it changing the spec completely?

**Comment by Duckle29** [comment]
This is backwards compatible with 12mm bolts, the nut-traps are just deeper to support the shorter bolts. However wait a bit with any merge as the print I just did has too shallow holes for the plate mount, which is weird

**Comment by mongrelion** [comment]
Fair enough. Maybe you can then add *WIP* to the title :)

**Comment by Duckle29** [comment]
Turns out I had dimensioned the PCB holes as deep as they could be with comfortable clearance, and the plate mount holes for 10mm bolts, however I forgot to compensate for the 2mm bolt head being part of the 10mm.
I, however, thought I had because the PCB mount bolts fit with length to spare but, yea. Should work now, though I'm printing a test piece to make sure.

**Comment by Duckle29** [comment]
That did the trick :)

**Comment by mongrelion** [comment]
Maybe you can also try to squash your commits :)

**Comment by Duckle29** [comment]
Done :)

**Review by drashna — APPROVED** [review]

**Comment by drashna** [comment]
Merge conflict :(

**Comment by Duckle29** [comment]
These changes are part of the other PR I have open, I'll close this.

**Pull request closed without merging**
